DROP DATABASE IF EXISTS pettifydb;
CREATE DATABASE pettifydb; 
USE pettifydb;

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  number BIGINT,
  location VARCHAR(255)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

COMMIT;
